```
# Matrices 2D en NumPy (ndarray)
.ndim
.shape
.size
.dtype
# Operaciones con matrices
# Producto Punto (matricial)
# ¿Qué pasa si las formas NO son compatibles?
```


Ver teoria adicional en el archivo numpy(p02).md

In [11]:
import numpy as np
# CONFIGURACION GENERAL_ Solo para visualización; Esto afecta a todos los print de numpy que hagas después
np.set_printoptions(precision=3, suppress=True)#precision=3→3decimales;suppress=True→no usar notación científica



In [ ]:
# Matriz: tensor de orden 2 (2D).
# 🟦 Matrices 2D en NumPy (ndarray)**

# En NumPy, una **matriz 2D** es simplemente un `ndarray` con `ndim = 2`, es decir:
# * Tiene **filas** y **columnas**
# * Se representa como una lista de listas
# * Es la base para trabajar algebra lineal básica

## 🔹1. Crear una matriz 2D

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Dimensiones:", A.ndim)    # 2
print("Forma:", A.shape)   # (2, 3)
print(A)
# [[1 2 3] [4 5 6]]

Dimensiones: 2
Forma: (2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
# Una matriz en NumPy es un arreglo de 2 dimensiones (2D) organizado en filas y columnas.
matriz3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz3x3) #matriz de tamaño 3×3,

# Este tipo de estructura resulta útil para representar datos con dos ejes naturales, por ejemplo: ventas (filas = productos, columnas = meses o regiones), almacenes/inventario (filas = ítems, columnas = variables como stock, costo, ubicación) e imágenes (una imagen en escala de grises suele modelarse como matriz 2D de intensidades; en color, se extiende a 3D al incluir canales).

productos = ["Laptop", "Monitor", "Teclado"]
regiones = ["Norte", "Sur", "Este", "Oeste"]

ventas = np.array([
    [15,  9, 10,  7],   # Laptop
    [ 8, 12,  6, 11],   # Monitor
    [25, 18, 22, 20],   # Teclado
])
print(ventas.ndim)    # 2 # Sigue siendo de 2D
print(ventas.shape)   # (3, 4)

# Interpretación:
print(ventas[0, 1]) # 9
# ventas[0, 1] es la venta de Laptop en Sur (9),
# y ventas[2, 0] es la venta de Teclado en Norte (25).


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 4)
9


In [ ]:
#CREAR ARRAYS AUTOMÁTICAMENTE

# Matriz identidad (1 en diagonal, 0 en el resto)
eye_matrix = np.eye(4)
print("\nMatriz identidad:")
print(eye_matrix)
    # La Matriz identidad es fundamental en álgebra lineal, ya que actúa como el elemento neutro para la multiplicación de matrices. Es decir, cualquier matriz multiplicada por la identidad (del tamaño adecuado) se mantiene sin cambios. Además, la identidad se utiliza para representar transformaciones que no alteran los vectores, y es clave en la resolución de sistemas de ecuaciones lineales y en la definición de inversas de matrices.

# Crear matriz diagonal
diag = np.diag([1, 2, 3, 4])
print("\nMatriz diagonal:")
print(diag)


Matriz identidad:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matriz diagonal:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
# 4️⃣ MATRICES CON VALORES ALEATORIOS
# ======================================================

# random.random → valores entre 0 y 1
random_matrix = np.random.random((2, 3))
print("\nMatriz aleatoria:")
print(random_matrix)

# enteros aleatorios
random_int = np.random.randint(1, 100, (3, 3)) # Matriz de 3x3 con enteros aleatorios entre 1 y 99 (100 no incluido)
print("\nMatriz aleatoria de enteros:")
print(random_int)

# Dividir cada elemento entre 100 (broadcasting)
matriz_dividida = random_int / 100
print("\nMatriz dividida entre 100:")
print(matriz_dividida)

# EJ:
# Matriz aleatoria de enteros:
# [[ 85  19  57]
#  [ 93  37  31]
#  [ 42  99  24]]
# Matriz dividida entre 100:
# [[0.85 0.19 0.57]
#  [0.93 0.37 0.31]
#  [0.42 0.99 0.24]]



Matriz aleatoria:
[[0.515 0.129 0.876]
 [0.377 0.756 0.614]]

Matriz aleatoria de enteros:
[[ 85  19  57]
 [ 93  37  31]
 [ 42 100  24]]

Matriz dividida entre 100:
[[0.85 0.19 0.57]
 [0.93 0.37 0.31]
 [0.42 1.   0.24]]


In [ ]:
# 7️⃣ TRANSPUESTA DE UNA MATRIZ
# ======================================================
M1 = np.array([[1, 2], [3, 4]])
print("\nTranspuesta:")
print(M1.T)


Transpuesta:
[[1 3]
 [2 4]]


In [ ]:
### 🔹 Propiedades importantes

# A = np.array([
#     [1, 2, 3],
#     [4, 5, 6]
# ])

print(A.ndim)   # 2  # número de dimensiones
print(A.shape)  # (2, 3) # (filas, columnas)
print(A.size)   # 6 # total de elementos filas × columnas
print(np.sum(A)) #21 # total acumulado de todos los valores (por ejemplo, ventas totales de todos los productos en todas las regiones/meses).
print(np.mean(A)) # 3.5 (promedio) # valor típico global; útil como referencia para comparar celdas o filas/columnas
print(np.std(A)) # 1.707825127659933 # dispersión global, qué tanto se alejan los valores del promedio; ayuda a detectar variabilidad alta/baja
print(f"{np.std(A):.3f}") # 1.708 
print(np.round(np.std(A), 2)) # 1.71
'''
Esa sumatoria/media/desviación sobre toda la matriz sirve para obtener métricas globales del conjunto de datos cuando la matriz representa una colección de valores numéricos.
'''
# En análisis real, a menudo se calcula por eje:  <3
#Por filas (producto):
print(np.sum(A, axis=1)) # [ 6 15] # Suma de cada fila (producto): Laptop (1+2+3=6) y Monitor (4+5+6=15)
print(np.mean(A, axis=1)) # [2. 5.] # Promedio de cada fila (producto): Laptop (3/3=1) y Monitor (15/3=5)
# Por columnas (mes/región):
print(np.sum(A, axis=0)) # [5 7 9] # Suma de cada columna (ej, región): Norte (1+4=5), Sur (2+5=7) y Este (3+6=9)
print(np.mean(A, axis=0)) # [2.5 3.5 4.5] # Promedio de cada columna.


2
(2, 3)
6
21
3.5
1.707825127659933
1.708
1.71
[ 6 15]
[2. 5.]
[5 7 9]
[2.5 3.5 4.5]


In [ ]:
# Cálculos Matriciales

# Suma de cada fila de la matriz B:
B = np.array([[1, 2, 3], 
              [4, 5, 6]])
# axis=1 suma de forma horizontal (por filas)
suma_filas = B.sum(axis=1)
print("\nSuma de cada fila de B:")
print(suma_filas) # Resultado: [6, 15] 
print(f"\nDonde la suma de la primera fila es {suma_filas[0]}, y la suma de la segunda fila es {suma_filas[1]}.")


Suma de cada fila de B:
[ 6 15]

Donde la suma de la primera fila es 6, y la suma de la segunda fila es 15.


In [ ]:
# Cálculos Matriciales
# Creamos dos matrices de 2x2
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[10, 20], 
              [30, 40]])

print("Suma de matrices:")
print(A + B)

print("\nResta de matrices:")
print(A - B)

print("\nMultiplicación elemento a elemento:")
print(A * B)

print("\nMultiplicación matricial:")
print(np.matmul(A, B))
# print("\n o tambien, Multiplicación con operador @:")
# print(A @ B)


Suma de matrices:
[[11 22]
 [33 44]]

Resta de matrices:
[[ -9 -18]
 [-27 -36]]

Multiplicación elemento a elemento:
[[ 10  40]
 [ 90 160]]

Multiplicación matricial:
[[ 70 100]
 [150 220]]


In [ ]:
# print("\nProducto de matrices:")
# print(np.dot(A, B))  #diferente a A*B, que es multiplicación elemento a elemento (Hadamard) y no el producto matricial tradicional.

A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])
# -------
# 1. Multiplicación ELEMENTO A ELEMENTO (Hadamard)
# Simplemente multiplica los que están en la misma posición.
hadamard = A * B 
print("\nMultiplicación elemento a elemento (A * B) (Hadamard):")
print(hadamard)
# Resultado: 
# [[ 5 12]
#  [21 32]]
# Logica: [[1*5, 2*6], [3*7, 4*8]] -> [[5, 12], [21, 32]]

'''
Para hacer multiplicación elemento a elemento, las matrices deben ser del mismo tamaño (misma forma). Es decir, deben tener el mismo número de filas y columnas (por ej ambas 3x3 o ambas 3x5). Si no son iguales, NumPy intentará hacer broadcasting (ajustarlas), pero si no puede, te dará error.
'''
# -------
# 2. PRODUCTO MATRICIAL (Tradicional / Álgebra Lineal)
# Usa la regla de "Fila por Columna".
producto_dot = np.dot(A, B)
print("\nProducto Matricial (np.dot):")
print(producto_dot)
# Resultado: 
# [[19, 22],
#  [43, 50]]
# Logica: [[(1*5 + 2*7), (1*6 + 2*8)], [(3*5 + 4*7), (3*6 + 4*8)]] -> [[19, 22], [43, 50]]
'''
NO tienen que ser iguales, pero deben ser compatibles.
La regla de oro: El número de columnas de A debe ser igual al número de filas de B.
Si  A es (3X2), B debe empezar por 2 (ej. 2X5). El resultado será una matriz de (3X5)
de forma (mXn) . (nXp) → (mXp) # Los números internos deben coincidir.
'''

### PENDIENTE CASOS PRACTICOS DE PRODUCTO MATRICIAL Y MULTIPLICACIÓN ELEMENTO A ELEMENTO




Multiplicación elemento a elemento (A * B) (Hadamard):
[[ 5 12]
 [21 32]]

Producto Matricial (np.dot):
[[19 22]
 [43 50]]


In [ ]:
### Producto punto (resultado = matriz → transformación lineal)
# Sea A una matriz de forma (m × n) y B una matriz de forma (n × p), entonces el producto matricial A @ B es una matriz de forma (m × p).
# A tiene forma (m × n)
# B tiene forma (n × p)
# A @ B #→ matriz de forma (m × p)
# El primer paso que debes comprobar antes de realizar la multiplicación matricial entre dos matrices A y B de NumPy es:
# El número de columnas de A debe ser igual al número de filas de B. (Requisito de Compatibilidad Dimensional)
# Ejemplo:  # (3×2) @ (2×3)
A = np.array([[1, 2],
                [3, 4],
                [5, 6]])  # Matriz A de forma (3 × 2)   
B = np.array([[7, 8, 9],
                [10, 11, 12]])  # Matriz B de forma (2 × 3)
C = A @ B  # Multiplicación matricial A @ B
print(C)
# Resultado:
# [[ 27  30  33]
#  [ 61  68  75]
#  [ 95 106 117]]

# Explicación del cálculo:
# Primera fila de A por cada columna de B:
# 1*7 + 2*10 = 27
# 1*8 + 2*11 = 30
# 1*9 + 2*12 = 33
# Segunda fila de A por cada columna de B:
# 3*7 + 4*10 = 61
# 3*8 + 4*11 = 68
# 3*9 + 4*12 = 75
# Tercera fila de A por cada columna de B:
# 5*7 + 6*10 = 95
# 5*8 + 6*11 = 106
# 5*9 + 6*12 = 117
# Por lo tanto, la matriz resultante C es:
# [[ 27  30  33]
#  [ 61  68  75]
#  [ 95 106 117]]


[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [ ]:
print("\n---- Ejemplo de función vectorizada ----")
#otro ejemplo de función vectorizada: # En una sola parte
def multiply_matrices(a):
    return a * 2
matrix = np.array([[1, 2], [3, 4]])
result = np.vectorize(multiply_matrices)(matrix)
print("Matriz original:\n", matrix)
print("Matriz multiplicada por 2:\n", result)

In [16]:
## 🟩 **2. Indexación y Slicing en matrices 2D**

### Acceder a un elemento:
# A[fila][columna]
# A[fila, columna]  # forma recomendada
A[0, 1]  # → 2

# **a. Acceder a una fila:**
A[0]         # fila completa
A[0, :]      # equivalente
print(A.dtype)  # int64 (depende del sistema) # tipo de dato

# **b. Acceder a una columna:**
A[:, 1]      # columna 1 → [2,5]

### Submatriz (slicing):
A[0:2, 1:3]   # filas 0-1 (en este caso todas), columnas 1-2
    # output: array([[2, 3], [5, 6]])

int64


array([[2, 3],
       [5, 6]])

In [ ]:
## 🟧 3 **# Operaciones con matrices**

### 🔸 1. Suma y Resta (elemento a elemento)
# Solo funciona si las matrices tienen **misma forma**.

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [10, 10, 10],
    [20, 20, 20]
])

print(A + B)
print(A - B)

### 🔸 2. Multiplicación por escalar

2 * A

# Opera elemento a elemento.
# [1*2, 2*2, 3*2], [4*2, 5*2, 6*2]

### 🔸 3. Producto Hadamard (multiplicación elemento a elemento)

# Importante: requiere **misma shape**.

A * B

[[11 12 13]
 [24 25 26]]
[[ -9  -8  -7]
 [-16 -15 -14]]


array([[ 10,  20,  30],
       [ 80, 100, 120]])

In [ ]:
### 🔸 4. # Producto Punto (matricial)
A = np.array([
    [1, 2],
    [4, 5]
])
B = np.array([
    [10, 10],
    [20, 20]
])

C = A @ B  # equivalente a A.dot(B)

# Trasponiendo matris para que las dimensiones sean compatibles
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [10, 10, 10],
    [20, 20, 20]
])

# Para que la multiplicación matricial sea válida, el número de columnas de A (3)
# debe coincidir con el número de filas de B. Trasponemos B para que tenga shape (3,2).
C = A @ B.T  # equivalente a A.dot(B.T)
print(C)

### 💡 **Regla de las dimensiones:**

# A tiene forma (m × n)
# B tiene forma (n × p)
# A @ B #→ matriz de forma (m × p)

# El primer paso que debes comprobar antes de realizar la multiplicación matricial entre dos matrices A y B de NumPy es:
# El número de columnas de A debe ser igual al número de filas de B. (Requisito de Compatibilidad Dimensional)
# de tal forma que:
# Si A es una matriz de dimensión m*n y B es una matriz de dimensión p*q, la multiplicación A*B solo es posible si: n = p


### 🟥 Ejemplo completo con matrices NO cuadradas

# Supongamos:
# `A` es (3×2)
# `B` es (2×3)

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])  # (3x2)

B = np.array([
    [7, 8, 9],
    [10,11,12]
]) # (2x3)

C = A @ B
print(C)
print(C.shape)

# [[ 27  30  33]
#  [ 61  68  75]
#  [ 95 106 117]]

# (3, 3)
# 💡 Funciona porque **las columnas de A = 2** y **las filas de B = 2**.


[[ 60 120]
 [150 300]]
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
(3, 3)


In [ ]:
### 🛑 # ¿Qué pasa si las formas NO son compatibles?

# Ejemplo:
# * A es (3×2)
# * B es (4×3)

# Si intentas:

try:
    A = np.array([
        [1, 2],
        [3, 4],
        [5, 6]
    ])  # (3x2)

    B = np.array([
        [7, 8, 9],
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]) # (4x3)

    C = A @ B
    print(C)
except ValueError as e:
    print(e) #
    #ValueError: shapes (3,2) and (4,3) not aligned


# Obtendrás error:
# Porque:
# 2 ≠ 4
# Importante ❗ Para multiplicar matrices, el **número de columnas de la primera** debe ser igual al **número de filas de la segunda**.

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)
