In [138]:
import numpy as np
print("✅ Numpy instalado!")
print("Versión:", np.__version__)

✅ Numpy instalado!
Versión: 2.3.5


In [139]:
a = np.array([2, 3, 7, 8, 5]) # Crear un arreglo ndarray a partir de una lista
type(a) # numpy.ndarray
# a.dtype # dtype('int64')
# print(a) # [2 3 7 8 5]

### Características del ndarray
# Similar a una lista, pero:
#    Tiene tipo homogéneo.
#    Es más rápido.
#    Tiene dimensión fija.

numpy.ndarray

In [140]:
# Especificar el tipo de dato al crear el ndarray
c = np.array([2, 3, 7, 8, 5], dtype=float)  # Especificar el tipo de dato (int, float, str, bool, np.complex, etc.)
c.dtype  # dtype('float64')
# print(a)  # [2. 3. 7. 8. 5.] # tipo float

dtype('float64')

In [141]:
# COPIAS vs VISTAS

# Demostración de que las variables pueden ser referencias al mismo objeto en memoria.
aa = np.array([2, 3, 7, 8, 5])
bb = aa  # bb es una referencia al mismo arreglo que aa
print(id(bb) == id(aa))  #True # bb es una referencia al mismo arreglo que aa
bb[2] = 33  # Modificar el tercer elemento a través de bb
print(aa)  # [ 2  3 33  8  5]  # aa refleja el cambio hecho a través de bb  
aa[0] = 0  # Modificar el primer elemento a través de aa
print(bb)  # [ 0  3 33  8  5]  # bb refleja el cambio hecho a través de aa
print(bb is aa)  #True # ambas variables apuntan al mismo objeto en memoria.

print("------------")
# Creando una copia independiente del arreglo
cc = bb.copy()  # cc es una copia independiente de aa
cc[2] = 55  # Modificar el tercer elemento de cc
print(cc is bb)  # False  # cc es una copia independiente de bb
print(bb)  # [ 0  3 33  8  5]  # bb no se ve afectado por el cambio en cc
print(cc)  # [ 0  3 55  8  5]  # cc es independiente de bb
print("------------")


# Por defecto, las operaciones de slicing y las funciones que crean nuevos arreglos devuelven vistas (views) del arreglo original, no copias independientes.
# Una vista es una referencia al mismo bloque de memoria que el arreglo original, por lo que los cambios en la vista afectan al original y viceversa.
# Si deseas crear una copia independiente del arreglo, puedes usar el método .copy().



# b = a[1:4]  # Vista del arreglo original (elementos desde el índice 1 hasta el 3)
# b[0] = 99   # Modificar el primer elemento de la vista
# print(a)  # [ 2 99  7  8  5]
# # Para crear una copia independiente:
# d = a[1:4].copy()  # Copia independiente del arreglo original
# d[0] = 55          # Modificar el primer elemento de la copia
# print(a)  # [ 2 99  7  8  5]                

True
[ 2  3 33  8  5]
[ 0  3 33  8  5]
True
------------
False
[ 0  3 33  8  5]
[ 0  3 55  8  5]
------------


In [ ]:
# Creacion y comportamiento de vistas en NumPy

aa = np.array([2, 3, 7, 8, 5])
bb = aa  ## bb es un alias o una referencia al objeto aa. Son exactamente el mismo objeto en memoria
# Formas de crear una vista:
cc = aa.view()  # bb es una vista del arreglo aa
cc = aa[:]  # bb es una vista del arreglo aa
print("------")
print(id(bb) == id(aa)) # True # bb es una referencia al mismo arreglo que aa
print(id(cc) == id(aa)) # False # cc es una vista, no una referencia directa (pero tampoco es una copia independiente)
print("------")
vw1_a = aa.view()  # vw_a es una vista del arreglo aa
vw2_a = aa.view()  # vw_a es una vista(2) del arreglo aa
vw1_b = bb.view()  # vw_a es una vista del arreglo bb (que es una referencia a aa)
# nota pero aa y bb siguen siendo referencias al mismo arreglo
print(vw1_a is aa)  # False  # vw_a es una vista, no una referencia directa
print(vw1_b is bb)  # False  # vw_a es una vista, no una referencia directa
# ...
print("--- Modificando el arreglo original ---")
aa[-1] = 99  # Modificar el último elemento del arreglo original
# Afecta a todas las vistas y referencias al mismo bloque de memoria
print(f"aa: {aa}")  
print(f"bb: {bb}") 
print(f"vw1_a: {vw1_a}")
print(f"vw2_a: {vw2_a}")
print(f"vw1_b: {vw1_b}")

print("--- Modificando una vista ---")
vw1_b[-2] = 55  
# Afecta a todas las vistas y referencias al mismo bloque de memoria
print(f"aa: {aa}")  
print(f"bb: {bb}") 
print(f"vw1_a: {vw1_a}")
print(f"vw2_a: {vw2_a}")
print(f"vw1_b: {vw1_b}")

# La principal ventaja de las vistas es la eficiencia, especialmente en operaciones complejas de reestructuración de datos, sin necesidad de copiar gigabytes de información.
# Las vistas ahorran una cantidad masiva de memoria en comparación con una copia completa (.copy()).

# Copia Completa (.copy()): Crea un bloque de datos nuevo en otra parte de la RAM. (Ocupa el doble de espacio).
# Vista (.view()): Solo crea un pequeño encabezado nuevo con metadatos. El espacio extra es insignificante (unos pocos bytes).


------
True
False
------
False
False
--- Modificando el arreglo original ---
aa: [ 2  3  7  8 99]
bb: [ 2  3  7  8 99]
vw1_a: [ 2  3  7  8 99]
vw2_a: [ 2  3  7  8 99]
vw1_b: [ 2  3  7  8 99]
--- Modificando una vista ---
aa: [ 2  3  7 55 99]
bb: [ 2  3  7 55 99]
vw1_a: [ 2  3  7 55 99]
vw2_a: [ 2  3  7 55 99]
vw1_b: [ 2  3  7 55 99]


In [159]:
# Reasignación de variables y referencias en NumPy
# Cuidado: reasignar la variable a un nuevo objeto rompe la referencia original.
aa = np.array([2, 3, 7, 8, 5])
bb = aa  # bb es una referencia al mismo arreglo que aa
print(id(bb) == id(aa)) # True
print("------")
aa = np.array([2, 3, 7, 8, 5])
print(id(bb) == id(aa)) # falso
# aa deja de apuntar al objeto original y apunta a un objeto completamente nuevo.

True
------
False


In [ ]:
## Crear arreglos con funciones de numpy
# Uso de zeros(), ones(), arange(), linspace(), random.rand(), etc.
print("Arreglo de ceros:")
# zeros(shape, dtype=float, order='C') permite crear un arreglo lleno de ceros.
b = np.zeros((3, 4), dtype=int)  # Crear un arreglo de ceros de 3 filas y 4 columnas
print(b)
# [[0 0 0 0]
#  [0 0 0 0]
#  [0 0 0 0]]
b.shape  # (3, 4)  # Dimensión del arreglo (2D con 3 filas y 4 columnas)
#---
print("Arreglo de unos:")
# ones(shape, dtype=float, order='C') permite crear un arreglo lleno de unos.
c = np.ones((2, 5), dtype=float)  # Crear un arreglo de unos de 2 filas y 5 columnas
print(c)
# [[1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]]
#---

# Arreglo unidimencional aleatorio de 5 elementos de 0 a 9
print("Arreglo unidimencional aleatorio:")
d1r = (np.random.rand(5)*10).astype(int) 
print(d1r) # [3 4 2 0 9]

# Crear un arreglo unidimensional de 5 elementos con valores aleatorios entre 0 y 1
#d1r = np.random.rand(5) 
#---
# arange([start, ]stop, [step, ]dtype=None) crea un arreglo con valores en un rango especificado.
print("Arreglo con arange() con step=2:")
d = np.arange(0, 21, 2)  # Crear un arreglo con valores desde 0 hasta 20
print(d)  # [ 0  2  4  6  8 10 12 14 16 18 20]
d.shape  # (11,)  # Dimensión del arreglo (1D con 11 elementos)
#---
# empty(shape, dtype=float, order='C') crea un arreglo sin inicializar (valores basura).
print("Arreglo vacío (valores basura):")
e = np.empty((2, 3), dtype=int)  # Crear un arreglo vacío de 2 filas y 3 columnas
print(e)
# [[ 2  3  7]
#  [ 8  5 99]]
#---
# random.rand(d0, d1, ..., dn) crea un arreglo con valores aleatorios entre 0 y 1.
# crear una matriz de 2x2 con valores aleatorios, enteros [0 a 10)
print("Arreglo con valores aleatorios:")
f = (np.random.rand(2, 2)*10).astype(int)  # Crear un arreglo de 2 filas y 2 columnas con valores aleatorios
print(f)
# [[0 4]
#  [9 6]]
#---
print("Arreglo con valores aleatorios enteros:")
# k= np.random.randint(0, 100, 10)  # Crear un arreglo de 10 elementos con valores aleatorios enteros entre 0 y 100
k= np.random.randint(0, 100, size=(2,2))  # Crear un arreglo de 2 filas y 2 columnas con valores aleatorios enteros entre 0 y 100
print(k) 
# [[23 67]
#  [45 12]]


Arreglo de ceros:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Arreglo de unos:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Arreglo unidimencional aleatorio:
[3 4 2 0 4]
Arreglo con arange() con step=2:
[ 0  2  4  6  8 10 12 14 16 18 20]
Arreglo vacío (valores basura):
[[ 2  3  7]
 [ 8  5 99]]
Arreglo con valores aleatorios:
[[3 1]
 [3 8]]
Arreglo con valores aleatorios enteros:
[[24 86]
 [66 99]]


In [144]:
### Propiedades importantes:
a = np.array([2, 3, 7, 8, 5])
a.dtype   # tipo de dato que almacena (int64, int32, float64...)
a.size    # 5 #cantidad total de elementos
a.ndim    # número de dimensiones (1 para vector)
a.shape   # tupla con la forma (5,)  ← 5 elementos en 1D

(5,)

In [145]:
# Agregar un elemento no es posible directamente.
# Pero se puede crear un nuevo arreglo con el elemento agregado:
b = np.append(a, 99)  # NUEVO ARREGLO con el elemento agregado
print(b)  # [ 2  3  7  8  5 99]
print(a)  # [2 3 7 8 5]
# esto es posible: a = np.append(a, 99) Pero apunta a otro arreglo en memoria


[ 2  3  7  8  5 99]
[2 3 7 8 5]


In [146]:
# Pero, manipular un elemento es posible:
print("Modificar un elemento del arreglo original:")
print(a)  # [2 3 7 8 5]
a[2] = 99 # Modificar el tercer elemento del arreglo original
print(a)  # [ 2  3 99  8  5]
print("------------")
# Indexación Básica (Slicing)
# Como tambien acceder a elementos (## 🟦 Indexación y slicing)
print(a[0])    # primer elemento
print(a[-1])   # último elemento
print(a[1:4])  # elementos desde el índice 1 hasta el 3 (excluye el 4) 
print(a[:3])   # primeros 3 elementos (incluye 0, 1, 2)
print(a[2:])   # desde el índice 2 hasta el final
print(a[::-1])    # arreglo invertido


Modificar un elemento del arreglo original:
[2 3 7 8 5]
[ 2  3 99  8  5]
------------
2
5
[ 3 99  8]
[ 2  3 99]
[99  8  5]
[ 5  8 99  3  2]


In [188]:
###########CUIDADO CON LAS VISTAS (views) EN NUMPY ###########
# Referencias en el caso de slices (slicing) en NumPy
# Cuando haces un slice (selección de rango) en un array de NumPy, por defecto, también se devuelve una vista:
ar = np.array([7, 1, 9, 6, 3])
ars = ar[:3]
print("Original ar  :", ar)    # [7 1 9 6 3]
print("Slice ars  :", ars)   # [7 1 9]
print("Demostraion de que ars es una vista de ar (ars.base):", ars.base)
    # Demostraion de que ars es una vista de ar (ars.base): [7 1 9 6 3]
print("---")
print("El valor de id(ar) es igual al valor de id(ars.base):", id(ar) == id(ars.base)) # True  # Mismas direcciones de memoria
print("ar y ars.base apuntan al mismo objeto:", ar is ars.base) # True # is sirve para comparar si dos variables apuntan al mismo objeto en memoria
# NO HACER ESTO: # print(id(ar) is id(ars.base))  # Resultado: False ### RESULTADO NO ESPERADO
# RAZÓN:
# 1. 'id(objeto)' se llama dos veces, creando dos objetos de tipo 'int' (números).
# 2. El operador 'is' comprueba si son el MISMO objeto en memoria, no si tienen el mismo valor.
# 3. Aunque los VALORES de los ID son idénticos (porque ar y ars.base son el mismo array),
#    Python trata las dos llamadas a 'id()' como dos OBJETOS enteros DISTINTOS.

print("---")
# Pero ar y ars comparten la misma memoria para esos tres primeros elementos.
ars[1] = 22
print("Modified ar origin :", ar)
print("Modified ars[1]=22 :", ars)
print("---")
ar[0] = 11
print("Modified ar[0]=11 :", ar)
print("Modified ars view :", ars)
print("---")

### NOTA: En las listas normales de Python no ocurre lo mismo: el slice de una lista es una copia superficial, no una vista.
print("IMPORTANTE: lista normal en Python no comparte memoria en slices:")
l = [7, 1, 9, 6, 3]
ls = l[:3]      # slice de lista
ls[1] = 22
print(l)   # [7, 1, 9, 6, 3]  ← no cambia
print(ls)  # [7, 22, 9]

Original ar  : [7 1 9 6 3]
Slice ars  : [7 1 9]
Demostraion de que ars es una vista de ar (ars.base): [7 1 9 6 3]
---
El valor de id(ar) es igual al valor de id(ars.base): True
ar y ars.base apuntan al mismo objeto: True
---
Modified ar origin : [ 7 22  9  6  3]
Modified ars[1]=22 : [ 7 22  9]
---
Modified ar[0]=11 : [11 22  9  6  3]
Modified ars view : [11 22  9]
---
IMPORTANTE: lista normal en Python no comparte memoria en slices:
[7, 1, 9, 6, 3]
[7, 22, 9]


In [147]:
# Subarreglos mediante Fancy Indexing (Selección no Contigua) #  [[]]
# Acceso a elementos (indexing) 
z = np.array([2, 3, 77, 8, 55, 10, 6, 1, 44, 9])
sub_z = z[[2, 4, 5, 8]] # Acceder a elementos en las posiciones 2 y 4
print(sub_z)  # [77 55 10 44]   # Subarreglo con los elementos en las posiciones 2 y 4
sub2_z = z[[True, True, False, True, False, False, True, True, False, True]]
print(sub2_z)  # [ 2  3  8  6  1  9]   # Subarreglo con los elementos donde el índice booleano es True
print("---- Máscara booleana ----")
# sub3_z = z[[True, False*8, True]] # ERROR
# Crea la lista (como mascara): [True] + [False, False, ..., False] (8 veces) + [True]
mascara_correcta = [True] + [False] * 8 + [True]
sub3_z = z[mascara_correcta]
print(sub3_z)  # [2 9]   # Subarreglo con los elementos donde el índice booleano es True
# fancy indexing es una técnica para acceder a múltiples elementos de un arreglo utilizando listas o arreglos de índices.
# El Fancy Indexing permite seleccionar un subconjunto de datos eligiendo elementos no contiguos (saltados o desordenados), a diferencia de la indexación básica que solo selecciona rangos continuos.

[77 55 10 44]
[2 3 8 6 1 9]
---- Máscara booleana ----
[2 9]


In [148]:
### Operaciones vectorizadas
## Suma y resta de vectores
# Operaciones aritméticas entre arreglos del mismo tamaño:
u = np.array([0, 1])
v = np.array([1, 0])
z = u + v     # array([1, 1])
# z = np.add(u, v)
print(z)

[1 1]


In [149]:
### Suma con escalar

u = np.array([1, 3, -1, 2])
z = u + 10     # array([11, 13,  9, 12])
print(z)

[11 13  9 12]


In [150]:
### Multiplicación por escalar

y = np.array([1, 3])
z = 2 * y     # array([2, 6])
print(z)

[2 6]


In [151]:
## 🟧 5. Producto Hadamard (multiplicación elemento a elemento)

u = np.array([1, 2])
v = np.array([3, 2])
z = u * v     # array([3, 4])
print(z)

[3 4]


In [152]:
## 🟨 6. Producto punto (dot product) (resultado = escalar)
# Es equivalente a la suma de los productos elemento a elemento.
# En álgebra lineal se denota como u·v o ⟨u, v⟩
# en álgebra lineal, el producto punto es simplemente un caso especial del producto matricial.
# se diferencia del producto Hadamard en que el resultado en el producto punto es un escalar.
u = np.array([1, 2])
v = np.array([3, 2])
# Internamente NumPy interpreta cada vector como una matriz 1×n y n×1.
z = u @ v   
# (1*3 + 2*2) = 7
print(z) # 7
# z = np.dot(u, v)  


7


In [153]:
### 🟩 7. Multiplicación de matrices (resultado = matriz → transformación lineal)
# Sea A una matriz de forma (m × n) y B una matriz de forma (n × p), entonces el producto matricial A @ B es una matriz de forma (m × p).
# A tiene forma (m × n)
# B tiene forma (n × p)
# A @ B #→ matriz de forma (m × p)
# El primer paso que debes comprobar antes de realizar la multiplicación matricial entre dos matrices A y B de NumPy es:
# El número de columnas de A debe ser igual al número de filas de B. (Requisito de Compatibilidad Dimensional)
# Ejemplo:  # (3×2) @ (2×3)
A = np.array([[1, 2],
                [3, 4],
                [5, 6]])  # Matriz A de forma (3 × 2)   
B = np.array([[7, 8, 9],
                [10, 11, 12]])  # Matriz B de forma (2 × 3)
C = A @ B  # Multiplicación matricial A @ B
print(C)
# Resultado:
# [[ 27  30  33]
#  [ 61  68  75]
#  [ 95 106 117]]
# Explicación del cálculo:
# Primera fila de A por cada columna de B:
# 1*7 + 2*10 = 27
# 1*8 + 2*11 = 30
# 1*9 + 2*12 = 33
# Segunda fila de A por cada columna de B:
# 3*7 + 4*10 = 61
# 3*8 + 4*11 = 68
# 3*9 + 4*12 = 75
# Tercera fila de A por cada columna de B:
# 5*7 + 6*10 = 95
# 5*8 + 6*11 = 106
# 5*9 + 6*12 = 117
# Por lo tanto, la matriz resultante C es:
# [[ 27  30  33]
#  [ 61  68  75]
#  [ 95 106 117]]

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [154]:
fnc_vector = np.vectorize(lambda x: x**2)
arr = np.array([1, 2, 3, 4, 5])
squared_arr = fnc_vector(arr)
print("Arreglo original:", arr)
print("Arreglo al cuadrado:", squared_arr)
print("---- Otro ejemplo de función vectorizada ----")
#otro ejemplo de función vectorizada: # En dos partes
def add_five(x):
    return x + 5
arr2 = np.array([10, 20, 30, 40])
fnc_vect_add_five = np.vectorize(add_five)
result_add_five = fnc_vect_add_five(arr2)
print("Arreglo original:", arr2)
print("Arreglo con 5 agregado a cada elemento:", result_add_five)
print("---- Otro ejemplo de función vectorizada ----")
#otro ejemplo de función vectorizada: # En una sola parte
def multiply_matrices(a):
    return a * 2
matrix = np.array([[1, 2], [3, 4]])
result = np.vectorize(multiply_matrices)(matrix)
print("Matriz original:\n", matrix)
print("Matriz multiplicada por 2:\n", result)

Arreglo original: [1 2 3 4 5]
Arreglo al cuadrado: [ 1  4  9 16 25]
---- Otro ejemplo de función vectorizada ----
Arreglo original: [10 20 30 40]
Arreglo con 5 agregado a cada elemento: [15 25 35 45]
---- Otro ejemplo de función vectorizada ----
Matriz original:
 [[1 2]
 [3 4]]
Matriz multiplicada por 2:
 [[2 4]
 [6 8]]
