In [ ]:
import numpy as np
# CONFIGURACION GENERAL_ Solo para visualización; Esto afecta a todos los print de numpy que hagas después
np.set_printoptions(precision=3, suppress=True)#precision=3→3decimales;suppress=True→no usar notación científica



A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.ndim)    # 2
print(A.shape)   # (2, 3)
print(A)

2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
# Tensor (en el uso común en programación/IA): normalmente se refiere a 3D o más.
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]]) #→ ndim = 3, shape = (1,4,2).

print(tensor.ndim)    # 3
print(tensor.shape)   # (1, 4, 2)
print(tensor)



3
(1, 4, 2)
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
