In [5]:
# 🟦 **Matrices 2D en NumPy (ndarray)**

# En NumPy, una **matriz 2D** es simplemente un `ndarray` con `ndim = 2`, es decir:
# * Tiene **filas** y **columnas**
# * Se representa como una lista de listas
# * Es la base para trabajar algebra lineal básica

## 🔹1. Crear una matriz 2D

import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A)
# [[1 2 3] [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [6]:
### 🔹 Propiedades importantes

print(A.ndim)   # 2  # número de dimensiones
print(A.shape)  # (2, 3) # (filas, columnas)
print(A.size)   # 6 # total de elementos filas × columnas
print(A.dtype)  # int64 (depende del sistema) # tipo de dato

## 🟩 **2. Indexación y Slicing en matrices 2D**

### Acceder a un elemento:
# A[fila][columna]
# A[fila, columna]  # forma recomendada

A[0, 1]  # → 2

# **a. Acceder a una fila:**

A[0]         # fila completa
A[0, :]      # equivalente

# **b. Acceder a una columna:**

A[:, 1]      # columna 1 → [2,5]

### Submatriz (slicing):

A[0:2, 1:3]   # filas 0-1, columnas 1-2

2
(2, 3)
6
int64


array([[2, 3],
       [5, 6]])

In [7]:
## 🟧 3 **Operaciones con matrices**

### 🔸 1. Suma y Resta (elemento a elemento)
# Solo funciona si las matrices tienen **misma forma**.

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [10, 10, 10],
    [20, 20, 20]
])

print(A + B)
print(A - B)

### 🔸 2. Multiplicación por escalar

2 * A

# Opera elemento a elemento.
# [1*2, 2*2, 3*2], [4*2, 5*2, 6*2]

### 🔸 3. Producto Hadamard (multiplicación elemento a elemento)

# Importante: requiere **misma shape**.

A * B

[[11 12 13]
 [24 25 26]]
[[ -9  -8  -7]
 [-16 -15 -14]]


array([[ 10,  20,  30],
       [ 80, 100, 120]])

In [8]:
### 🔸 4. Producto Punto (matricial)
A = np.array([
    [1, 2],
    [4, 5]
])
B = np.array([
    [10, 10],
    [20, 20]
])

C = A @ B  # equivalente a A.dot(B)

# Trasponiendo matris para que las dimensiones sean compatibles
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [10, 10, 10],
    [20, 20, 20]
])

# Para que la multiplicación matricial sea válida, el número de columnas de A (3)
# debe coincidir con el número de filas de B. Trasponemos B para que tenga shape (3,2).
C = A @ B.T  # equivalente a A.dot(B.T)
print(C)

### 💡 **Regla de las dimensiones:**

# A tiene forma (m × n)
# B tiene forma (n × p)
# A @ B #→ matriz de forma (m × p)

# El primer paso que debes comprobar antes de realizar la multiplicación matricial entre dos matrices A y B de NumPy es:
# El número de columnas de A debe ser igual al número de filas de B. (Requisito de Compatibilidad Dimensional)
# de tal forma que:
# Si A es una matriz de dimensión m*n y B es una matriz de dimensión p*q, la multiplicación A*B solo es posible si: n = p


### 🟥 Ejemplo completo con matrices NO cuadradas

# Supongamos:
# `A` es (3×2)
# `B` es (2×3)

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])  # (3x2)

B = np.array([
    [7, 8, 9],
    [10,11,12]
]) # (2x3)

C = A @ B
print(C)
print(C.shape)

# [[ 27  30  33]
#  [ 61  68  75]
#  [ 95 106 117]]

# (3, 3)
# 💡 Funciona porque **las columnas de A = 2** y **las filas de B = 2**.


[[ 60 120]
 [150 300]]
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
(3, 3)


In [9]:
### 🛑 ¿Qué pasa si las formas NO son compatibles?

# Ejemplo:
# * A es (3×2)
# * B es (4×3)

# Si intentas:

try:
    A = np.array([
        [1, 2],
        [3, 4],
        [5, 6]
    ])  # (3x2)

    B = np.array([
        [7, 8, 9],
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]) # (4x3)

    C = A @ B
    print(C)
except ValueError as e:
    print(e) #
    #ValueError: shapes (3,2) and (4,3) not aligned


# Obtendrás error:
# Porque:
# 2 ≠ 4
# Importante ❗ Para multiplicar matrices, el **número de columnas de la primera** debe ser igual al **número de filas de la segunda**.

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)
