In [ ]:
# Indexación booleana
array = np.array([10,20,30,40,50])
bool_index = array > 25
print(bool_index)
print(type(bool_index))
# [False False  True  True  True]

# Indexación con lista de índices
index = [2,0,3]
print(array[index])
# Obtener un valor específico de una matriz 2D
array = np.random.randint(1, 10, size=(3,3))
print(array)
print(array[0,1])
print(array[:2,:2])

In [ ]:
# HAY OPERACIONES QUE RETORNAN COPIAS DE LOS DATOS, OTRAS RETORNAN VISTAS (REFERENCIAS) A LOS DATOS ORIGINALES.

# Manipulación de vistas y copias
array_x = np.arange(10)
view_y = array_x[1:3] # Slice devuelve una vista (referencia)
print(array_x)
print(view_y)
array_x[1:3] = [10,11] # Modificar el array original también modifica la vista
print(array_x)
print(view_y) # Se refleja el cambio en la vista debido a que es una referencia.
# [0 1 2 3 4 5 6 7 8 9]
# [1 2]
# [ 0 10 11  3  4  5  6  7  8  9]
# [10 11]

array_x = np.arange(10)
copy_x = array_x[[1,2]] # Indicar posiciones específicas devuelve una copia
print(array_x)
print(copy_x)
array_x[1:3] = [10,11] # Modificar el array original NO modifica la copia porque es una copia independiente
print(array_x)
print(copy_x)
# [0 1 2 3 4 5 6 7 8 9]
# [1 2]
# [ 0 10 11  3  4  5  6  7  8  9]
# [1 2]



In [ ]:
# Valores unicos en un array  y su conteo
survey_responses = np.array(["bueno", "excelente", "malo",
                             "bueno", "malo", "excelente",
                             "bueno", "bueno", "malo",
                             "excelente"])

# print(np.unique(survey_responses))
# ['bueno' 'excelente' 'malo']
unique_elements, counts = np.unique(survey_responses, return_counts=True)
print(unique_elements)
print(counts)
# ['bueno' 'excelente' 'malo']
# [4 3 3]

In [ ]:
# Broadcasting & Operaciones

# Ejemplo: aplicar un descuento a una lista de precios 
prices = np.array([100,200,300]) # precios de 3 productos
discount = np.array([0.9]) # descuento del 10%
discount_prices = prices * discount
print("Precios originales:", prices)
print("Descuento aplicado:", discount)
print("Precios con descuento:", discount_prices)

# Ejemplo: sumar un incremento a una matriz de precios
prices = np.random.randint(100,500, size=(3,3))
increment = np.array([10,20,30])
increment_prices = prices + increment
print(prices)
print(increment_prices)

# Ejemplo: operaciones lógicas con broadcasting
array = np.array([1,2,3,4,5])
print(np.all(array > 0)) # True
print(np.all(array > 1)) # False
print(np.any(array > 3)) # True 
print(np.any(array > 7)) # False 

# Concatenación de arrays
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated_a = np.concatenate((array_a, array_a))
print("Concatenación de array_a consigo mismo:")
print(concatenated_a)
print("Concatenación de array_a y array_b:")
concatenated_ab = np.concatenate((array_a, array_b))
print(concatenated_ab)
# Concatenación de array_a y array_b:
# [1 2 3 4 5 6]
# Igual al apilamiento horizontal, pero sin necesidad de que las dimensiones coincidan.


# Apilamiento de arrays
# Apilamiento horizontal (hstack)
stacked_h = np.hstack((array_a, array_b))
print("Apilamiento horizontal de array_a y array_b:")
print(stacked_h)
# Apilamiento horizontal de array_a y array_b:
# [1 2 3 4 5 6]
# Apilamiento vertical (vstack)
stacked_v = np.vstack((array_a, array_b))
print("Apilamiento vertical de array_a y array_b:")
print(stacked_v)
# Apilamiento vertical de array_a y array_b:
# [[1 2 3]
#  [4 5 6]]
# El apilamiento es útil para combinar datos de diferentes fuentes o para preparar datos para modelos de machine learning.

# División de arrays con np.split()
array_long = np.arange(1,10)
print("Array original:")
print(array_long)
# Array original:
# [1 2 3 4 5 6 7 8 9]
split_array = np.split(array_long,3) # Divide el array en 3 partes iguales
print(split_array) # [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]



In [34]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
transposed_matrix = matrix.T
print(matrix)
print(transposed_matrix)
#--------------

array = np.arange(1,13)
reshaped_array = array.reshape(3,4)
print(array)
print(reshaped_array)
# -------------
reversed_array = array[::-1]
print(array)
print(reversed_array )
#---------------
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flattened_array = matrix.flatten()
print(matrix)
print(flattened_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# Otras operaciones matriciales
A = np.array([[1,2],[3,4]])
det_A = np.linalg.det(A) # Determinante
    # La determinante es un número que nos dice si la matriz es invertible o no. Si el determinante es 0, la matriz no tiene inversa.
inv_A = np.linalg.inv(A)
    # La inversa de una matriz A es otra matriz que, cuando se multiplica por A, da como resultado la matriz identidad. Solo existe si el determinante de A es diferente de 0.
print(A)
print(det_A)
print(inv_A)

#Resolver Ax = b
b = np.array([9,11])
x = np.linalg.solve(A,b)
print(x)

In [ ]:
datos_simulados = np.random.normal(0, 1, 1000)
media_simulada = np.mean(datos_simulados)
desviacion_simulada = np.std(datos_simulados)

print("Media de los datos simulados:", media_simulada)
print("Desviación estándar de los datos simulados:", desviacion_simulada)

```
Vector = lista ordenada de números //Representa:posición,datos,características
Matriz = tabla rectangular de números //Representa:datos estructurados,características,sistemas matemáticos
Tensor = generalización de matrices a más dimensiones //Representa:posición,datos,caracter

datos estructurados


.array()  // crear arrays
.type() // tipo de dato
.dtype // tipo de dato
.size // número de elementos
.ndim // número de dimensiones
.shape // forma del array
.id() // id en memoria
.view() // vista del array
.zeros() // array de ceros
.ones()  // array de unos
.arange() // array con rango
.linspace() // array con rango lineal
.random() // valores aleatorios
.eye() // matriz identidad
.diag() // matriz diagonal
rand() // números aleatorios
append() // añadir elementos
.base // array original de una vista
mascara // sirve para filtrar elementos de un array
dot() = producto punto
@ = multiplicación matricial
T = transpuesta

### Operaciones vectorizadas // operaciones elemento a elemento
### Suma con escalar /// Resta con escalar
### Multiplicación por escalar // División por escalar
### Producto Hadamard // elemento a elemento
### Producto punto // dot product
### Multiplicación de matrices // transformación lineal


no vistos:
.reshape() // cambiar forma
### Funciones universales (ufuncs) // funciones

Ver teoria adicional en el archivo numpy(p01).md
```

In [16]:
import numpy as np
# CONFIGURACION GENERAL_ Solo para visualización; Esto afecta a todos los print de numpy que hagas después
np.set_printoptions(precision=3, suppress=True)#precision=3→3decimales;suppress=True→no usar notación científica


print("✅ Numpy instalado!")
print("Versión:", np.__version__)

✅ Numpy instalado!
Versión: 2.4.2


In [ ]:
# Escalar: tensor de orden 0 (0D)
escalar = np.array(42)

print(type(escalar))   # <class 'numpy.ndarray'>
print(escalar)         # 42
print(escalar.ndim)    # 0
print(escalar.shape)   # ()
print(escalar.dtype)   # por ejemplo int64 (depende del sistema)

#“Dimensión” en NumPy equivale al número de ejes del arreglo (ndim). Un 0D (cero dimensiones) tiene ndim == 0 y su shape es una tupla vacía (), porque no hay filas ni columnas: solo un valor.


En programación y álgebra lineal, “escalar” suele significar “valor individual” (no tiene dirección asociada) que puede multiplicar o sumar a vectores/matrices elemento a elemento.  
Un escalar es un único valor numérico que representa “cuánto” de algo, pero no “hacia dónde”.  
En álgebra lineal, ese valor sirve como factor para afectar otros objetos numéricos (vectores y matrices) sin cambiar su estructura, solo sus valores.  
En NumPy, 42 es un escalar como concepto matemático; y np.array(42) es ese escalar “envuelto” como un arreglo 0D

In [ ]:
# Vector: tensor de orden 1 (1D).
vector = np.array([2, 3, 7, 8, 5]) # Crear un arreglo ndarray a partir de una lista
    #los vectores son arreglos unidimensionales, lo que significa que tienen una sola dimensión (ndim == 1) y su forma (shape) es una tupla con un solo elemento que indica el número de elementos en esa dimensión. En este caso, el vector tiene 5 elementos, por lo que su shape es (5,).
    # Los VECTORES en PANDA son llamados Series, que son estructuras de datos unidimensionales con etiquetas (índices) para cada elemento. Las Series pueden contener datos de diferentes tipos, pero cada elemento dentro de una Serie debe ser del mismo tipo. En cambio, los vectores en NumPy (ndarray) son arreglos homogéneos que pueden contener solo un tipo de dato, como enteros o flotantes.
type(vector) # numpy.ndarray //(un arreglo de NumPy)
# vector.dtype # dtype('int64')
# print(vector) # [2 3 7 8 5]
print(vector.ndim)    # 1
print(vector.shape)   # (5,)
print(vector.dtype)   # por ejemplo int64 (depende del sistema)

### Características del ndarray
# Similar a una lista, pero:
#    Tiene tipo homogéneo.
#    Es más rápido.
#    Tiene dimensión fija.

'''
Este vector contiene varios elementos y tiene una dimensión (un solo eje), por lo que vector.ndim sería 1 y vector.shape sería (5,)
'''

1
(5,)
int64


'\nEste vector contiene varios elementos y tiene una dimensión (un solo eje), por lo que vector.ndim sería 1 y vector.shape sería (5,)\n'

In [ ]:
# NumPy SIEMPRE homogéneo
np.array([1, 2, "tres"])
# → y convierte todo a string:
# salida: array(['1','2','tres']) # los elementos se convierten al mismo tipo, en este caso a string, para mantener la homogeneidad del arreglo.
# no como objeto mixto como en pandas, donde se permite mezclar tipos de datos en una Serie, pero el dtype se convierte en object para indicar que puede contener cualquier tipo de dato. En NumPy, la homogeneidad es estricta, por lo que todos los elementos deben ser del mismo tipo, y si se mezclan tipos, NumPy los convierte al tipo más general (en este caso, string) para mantener la consistencia del arreglo.

array(['1', '2', 'tres'], dtype='<U21')

In [3]:
# Un vector puede representar coordenadas
posicion = np.array([4, 2, 7])
print("\nCoordenadas espaciales:", posicion)


Coordenadas espaciales: [4 2 7]


In [21]:
# CREACIÓN DE ARRAYS EN NUMPY
# > Desde lista o tupla
# > Funciones de creación de arrays
# > Arrays con valores aleatorios
# > Replicación  y transformación de arrays
# > Unión y apilamiento(combinacion) de arrays
# > Funciones universales (ufuncs) // funciones
# > Desde archivos o buffers

# A partir de listas o tuplas: ############
lista = [1, 2, 3, 4]
array_lista = np.array(lista)
print("\nArray desde lista:")
print(array_lista)

tupla = (5, 6, 7)
array_tupla = np.array(tupla)
print("\nArray desde tupla:")
print(array_tupla)

# matriz desde lista de listas 
matriz = np.array([[1, 2], [3, 4]])
print("\nMatriz desde lista de listas:")
print(matriz)



Array desde lista:
[1 2 3 4]

Array desde tupla:
[5 6 7]

Matriz desde lista de listas:
[[1 2]
 [3 4]]


In [22]:
# Funciones de creación de arrays: ###########
array_ceros = np.zeros((3, 4))  # Matriz de ceros
print("\nMatriz de ceros:")
print(array_ceros)

array_unos = np.ones((2, 5))    # Matriz de unos
print("\nMatriz de unos:")
print(array_unos)

linspace_array = np.linspace(0, 1, 5)  # 5 números entre 0 y 1
print("\nArray con linspace:")
print(linspace_array)

# np.arange(inicio, fin)
array_arange = np.arange(10)
print("\nArreglo con arange (secuencia numerica):")
print(array_arange)

eye_matriz = np.eye(4)  # Matriz identidad de 4x4
print("\nMatriz identidad:")
print(eye_matriz)

diag_matriz = np.diag([1, 2, 3, 4])  # Matriz diagonal con los elementos dados
print("\nMatriz diagonal:")
print(diag_matriz)



Matriz de ceros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Matriz de unos:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Array con linspace:
[0.   0.25 0.5  0.75 1.  ]

Arreglo con arange (secuencia numerica):
[0 1 2 3 4 5 6 7 8 9]

Matriz identidad:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matriz diagonal:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [23]:
# Array con valores aleatorios: ###########
array_aleatorio = np.random.random((3, 4))  # Matriz de valores aleatorios entre 0 y 1
print("\nArray 3x4 con valores aleatorios:")
print(array_aleatorio)

random_int = np.random.randint(1, 10, (3, 3))
print("\nMatriz 3x3 de enteros aleatorios entre 1 y 9:")
print(random_int)

normal = np.random.normal(0, 1, (2, 2))
print("\nMatriz 2x2 de valores aleatorios con distribución normal (media=0, desviación estándar=1):")
print(normal)


Array 3x4 con valores aleatorios:
[[0.212 0.856 0.489 0.015]
 [0.032 0.202 0.816 0.812]
 [0.412 0.042 0.258 0.711]]

Matriz 3x3 de enteros aleatorios entre 1 y 9:
[[9 4 5]
 [9 8 7]
 [8 9 7]]

Matriz 2x2 de valores aleatorios con distribución normal (media=0, desviación estándar=1):
[[ 0.434  0.186]
 [ 1.581 -2.04 ]]


In [20]:
# CREACIÓN DE ARRAYS EN NUMPY

# Replicación y modificación: ############
base = np.array([1, 2, 3, 4])

# repetir valores
replicated = np.tile(base, 3)  # Replicar el array 3 veces
print("\nArray replicado 3 veces:")
print(replicated)

# repoclar como matriz:
replicated_matrix = np.tile(base, (3, 1))  # Replicar el array como matriz de 3 filas
print("\nArray replicado como matriz de 3 filas:")
print(replicated_matrix)

# cambiar forma (reshape)
reshaped = base.reshape(2, 2)  # Cambiar la forma a 2x2
print("\nArray reshaped a 2x2:")
print(reshaped)




Array replicado 3 veces:
[1 2 3 4 1 2 3 4 1 2 3 4]

Array replicado como matriz de 3 filas:
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

Array reshaped a 2x2:
[[1 2]
 [3 4]]


In [ ]:
# Union y combinacion de arrays: ############

# concatenar arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenar por defecto (axis=0, es decir, a lo largo de las filas)
concatenated = np.concatenate([array1, array2])
print("\nArrays concatenados:")
print(concatenated)

# concatenar matrices       
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
concatenated_matrix = np.concatenate([matrix1, matrix2], axis=0)  # Concatenar por filas
print("\nMatrices concatenadas por filas:")
print(concatenated_matrix)

# Concatenar por columnas (axis=1)
concatenated_matrix_cols = np.concatenate([matrix1, matrix2], axis=1)  # Concatenar por columnas
print("\nMatrices concatenadas por columnas:")
print(concatenated_matrix_cols)
# Apilar arrays (stacking)
stacked = np.stack([array1, array2])  # Apilar por defecto (axis=0)
print("\nArrays apilados:")
print(stacked)

# Apilar por columnas (axis=1)
stacked_cols = np.stack([array1, array2], axis=1)
print("\nArrays apilados por columnas:")
print(stacked_cols)

# apilar verticalmente
vstacked = np.vstack([array1, array2])  # Apilar verticalmente (equivalente a stack con axis=0)
print("\nArrays apilados verticalmente:")
print(vstacked)

# apilar horizontalmente
hstacked = np.hstack([array1, array2])  # Apilar horizontalmente (equivalente a stack con axis=1)
print("\nArrays apilados horizontalmente:")
print(hstacked)

# Funciones universales (ufuncs) // funciones
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
suma = np.add(array_a, array_b)  # Suma elemento a elemento
print("\nSuma de arrays:")
print(suma)


In [ ]:
# CREAR ARRAYS DESDE ARCHIVOS O BUFFERS

# desde texto (simula archivo) ####
texto = "1 2 3 4 5"
from_text = np.fromstring(texto, sep=" ")
print("\nDesde texto:")
print(from_text)

# desde bytes crudos
bytes_data = b'\x01\x02\x03\x04'
from_bytes = np.frombuffer(bytes_data, dtype=np.uint8)
print("\nDesde bytes:")
print(from_bytes)

In [ ]:
# Especificar el tipo de dato al crear el ndarray
c = np.array([2, 3, 7, 8, 5], dtype=float) 
    # Especificar el tipo de dato (int, float, str, bool, np.complex, etc.)
c.dtype  # dtype('float64')
# print(a)  # [2. 3. 7. 8. 5.] # tipo float

dtype('float64')

In [ ]:
'''
uint8: entero sin signo de 8 bits; rango 0–255. Sin valores negativos. Útil en datos como imágenes (valores de píxel) y para ahorrar memoria.

float32: flotante de 32 bits (precisión simple); usa menos memoria y puede ser más rápido, pero con menor precisión numérica (aunque puede ser suficiente).

float64: flotante de 64 bits (doble precisión); suele ser el por defecto en NumPy y ofrece mayor precisión, a costa de más memoria.

int64: entero con signo de 64 bits; útil para conteos y valores enteros grandes (sin decimales).
'''
a = np.array([0, 255], dtype=np.uint8)
b = np.array([1.2, 3.4], dtype=np.float32)
c = np.array([1.2, 3.4], dtype=np.float64)
d = np.array([1, 2, 3], dtype=np.int64)
print(a.dtype, b.dtype, c.dtype, d.dtype)

double_array = np.array([1,2,3], dtype='d')
print(double_array)

z = np.array(3, dtype=np.uint8) # 3
z = z.astype(np.float64)
print(z) #3.0
# astype() es un método de NumPy que convierte (castea) el tipo de dato (dtype) de un ndarray a otro, normalmente creando un nuevo arreglo con el tipo solicitado (por defecto hace copia).

uint8 float32 float64 int64
3.0


In [5]:
# COPIAS vs VISTAS

# Demostración de que las variables pueden ser referencias al mismo objeto en memoria.
aa = np.array([2, 3, 7, 8, 5])
bb = aa  # bb es una referencia al mismo arreglo que aa
print(id(bb) == id(aa))  #True # bb es una referencia al mismo arreglo que aa
bb[2] = 33  # Modificar el tercer elemento a través de bb
print(aa)  # [ 2  3 33  8  5]  # aa refleja el cambio hecho a través de bb  
aa[0] = 0  # Modificar el primer elemento a través de aa
print(bb)  # [ 0  3 33  8  5]  # bb refleja el cambio hecho a través de aa
print(bb is aa)  #True # ambas variables apuntan al mismo objeto en memoria.

print("------------")
# Creando una copia independiente del arreglo
cc = bb.copy()  # cc es una copia independiente de aa
cc[2] = 55  # Modificar el tercer elemento de cc
print(cc is bb)  # False  # cc es una copia independiente de bb
print(bb)  # [ 0  3 33  8  5]  # bb no se ve afectado por el cambio en cc
print(cc)  # [ 0  3 55  8  5]  # cc es independiente de bb
print("------------")


# Por defecto, las operaciones de slicing y las funciones que crean nuevos arreglos devuelven vistas (views) del arreglo original, no copias independientes.
# Una vista es una referencia al mismo bloque de memoria que el arreglo original, por lo que los cambios en la vista afectan al original y viceversa.
# Si deseas crear una copia independiente del arreglo, puedes usar el método .copy().



# b = a[1:4]  # Vista del arreglo original (elementos desde el índice 1 hasta el 3)
# b[0] = 99   # Modificar el primer elemento de la vista
# print(a)  # [ 2 99  7  8  5]
# # Para crear una copia independiente:
# d = a[1:4].copy()  # Copia independiente del arreglo original
# d[0] = 55          # Modificar el primer elemento de la copia
# print(a)  # [ 2 99  7  8  5]                

True
[ 2  3 33  8  5]
[ 0  3 33  8  5]
True
------------
False
[ 0  3 33  8  5]
[ 0  3 55  8  5]
------------


In [6]:
# Creacion y comportamiento de vistas en NumPy

aa = np.array([2, 3, 7, 8, 5])
bb = aa  ## bb es un alias o una referencia al objeto aa. Son exactamente el mismo objeto en memoria
# Formas de crear una vista:
cc = aa.view()  # bb es una vista del arreglo aa
cc = aa[:]  # bb es una vista del arreglo aa
print("------")
print(id(bb) == id(aa)) # True # bb es una referencia al mismo arreglo que aa
print(id(cc) == id(aa)) # False # cc es una vista, no una referencia directa (pero tampoco es una copia independiente)
print("------")
vw1_a = aa.view()  # vw_a es una vista del arreglo aa
vw2_a = aa.view()  # vw_a es una vista(2) del arreglo aa
vw1_b = bb.view()  # vw_a es una vista del arreglo bb (que es una referencia a aa)
# nota pero aa y bb siguen siendo referencias al mismo arreglo
print(vw1_a is aa)  # False  # vw_a es una vista, no una referencia directa
print(vw1_b is bb)  # False  # vw_a es una vista, no una referencia directa
# ...
print("--- Modificando el arreglo original ---")
aa[-1] = 99  # Modificar el último elemento del arreglo original
# Afecta a todas las vistas y referencias al mismo bloque de memoria
print(f"aa: {aa}")  
print(f"bb: {bb}") 
print(f"vw1_a: {vw1_a}")
print(f"vw2_a: {vw2_a}")
print(f"vw1_b: {vw1_b}")

print("--- Modificando una vista ---")
vw1_b[-2] = 55  
# Afecta a todas las vistas y referencias al mismo bloque de memoria
print(f"aa: {aa}")  
print(f"bb: {bb}") 
print(f"vw1_a: {vw1_a}")
print(f"vw2_a: {vw2_a}")
print(f"vw1_b: {vw1_b}")

# La principal ventaja de las vistas es la eficiencia, especialmente en operaciones complejas de reestructuración de datos, sin necesidad de copiar gigabytes de información.
# Las vistas ahorran una cantidad masiva de memoria en comparación con una copia completa (.copy()).

# Copia Completa (.copy()): Crea un bloque de datos nuevo en otra parte de la RAM. (Ocupa el doble de espacio).
# Vista (.view()): Solo crea un pequeño encabezado nuevo con metadatos. El espacio extra es insignificante (unos pocos bytes).


------
True
False
------
False
False
--- Modificando el arreglo original ---
aa: [ 2  3  7  8 99]
bb: [ 2  3  7  8 99]
vw1_a: [ 2  3  7  8 99]
vw2_a: [ 2  3  7  8 99]
vw1_b: [ 2  3  7  8 99]
--- Modificando una vista ---
aa: [ 2  3  7 55 99]
bb: [ 2  3  7 55 99]
vw1_a: [ 2  3  7 55 99]
vw2_a: [ 2  3  7 55 99]
vw1_b: [ 2  3  7 55 99]


In [7]:
# Reasignación de variables y referencias en NumPy
# Cuidado: reasignar la variable a un nuevo objeto rompe la referencia original.
aa = np.array([2, 3, 7, 8, 5])
bb = aa  # bb es una referencia al mismo arreglo que aa
print(id(bb) == id(aa)) # True
print("------")
aa = np.array([2, 3, 7, 8, 5])
print(id(bb) == id(aa)) # falso
# aa deja de apuntar al objeto original y apunta a un objeto completamente nuevo.

True
------
False


In [8]:
## Crear arreglos con funciones de numpy
# Uso de zeros(), ones(), arange(), linspace(), random.rand(), etc.
print("Arreglo de ceros:")
# zeros(shape, dtype=float, order='C') permite crear un arreglo lleno de ceros.
b = np.zeros((3, 4), dtype=int)  # Crear un arreglo de ceros de 3 filas y 4 columnas
print(b)
# [[0 0 0 0]
#  [0 0 0 0]
#  [0 0 0 0]]
b.shape  # (3, 4)  # Dimensión del arreglo (2D con 3 filas y 4 columnas)
#---
print("Arreglo de unos:")
# ones(shape, dtype=float, order='C') permite crear un arreglo lleno de unos.
c = np.ones((2, 5), dtype=float)  # Crear un arreglo de unos de 2 filas y 5 columnas
print(c)
# [[1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]]
#---

# Arreglo unidimencional aleatorio de 5 elementos de 0 a 9
print("Arreglo unidimencional aleatorio:")
d1r = (np.random.rand(5)*10).astype(int) 
print(d1r) # [3 4 2 0 9]

# Crear un arreglo unidimensional de 5 elementos con valores aleatorios entre 0 y 1
#d1r = np.random.rand(5) 
#---
# arange([start, ]stop, [step, ]dtype=None) crea un arreglo con valores en un rango especificado.
print("Arreglo con arange() con step=2:")
d = np.arange(0, 21, 2)  # Crear un arreglo con valores desde 0 hasta 20
print(d)  # [ 0  2  4  6  8 10 12 14 16 18 20]
d.shape  # (11,)  # Dimensión del arreglo (1D con 11 elementos)
#---
# empty(shape, dtype=float, order='C') crea un arreglo sin inicializar (valores basura).
print("Arreglo vacío (valores basura):")
e = np.empty((2, 3), dtype=int)  # Crear un arreglo vacío de 2 filas y 3 columnas
print(e)
# [[ 2  3  7]
#  [ 8  5 99]]
#---
# random.rand(d0, d1, ..., dn) crea un arreglo con valores aleatorios entre 0 y 1.
# crear una matriz de 2x2 con valores aleatorios, enteros [0 a 10)
print("Arreglo con valores aleatorios:")
f = (np.random.rand(2, 2)*10).astype(int)  # Crear un arreglo de 2 filas y 2 columnas con valores aleatorios
print(f)
# [[0 4]
#  [9 6]]
#---
print("Arreglo con valores aleatorios enteros:")
# k= np.random.randint(0, 100, 10)  # Crear un arreglo de 10 elementos con valores aleatorios enteros entre 0 y 100
k= np.random.randint(0, 100, size=(2,2))  # Crear un arreglo de 2 filas y 2 columnas con valores aleatorios enteros entre 0 y 100
print(k) 
# [[23 67]
#  [45 12]]


Arreglo de ceros:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Arreglo de unos:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Arreglo unidimencional aleatorio:
[4 7 3 0 1]
Arreglo con arange() con step=2:
[ 0  2  4  6  8 10 12 14 16 18 20]
Arreglo vacío (valores basura):
[[9218868437227405311   -4503599627370497 4611686018427387904]
 [4372995238176751616    4503599627370496                   1]]
Arreglo con valores aleatorios:
[[9 9]
 [5 5]]
Arreglo con valores aleatorios enteros:
[[25  6]
 [63 66]]


In [9]:
### Propiedades importantes:
a = np.array([2, 3, 7, 8, 5])
a.dtype   # tipo de dato que almacena (int64, int32, float64...)
a.size    # 5 #cantidad total de elementos
a.ndim    # número de dimensiones (1 para vector)
a.shape   # tupla con la forma (5,)  ← 5 elementos en 1D

(5,)

In [10]:
# Agregar un elemento no es posible directamente.
# Pero se puede crear un nuevo arreglo con el elemento agregado:
b = np.append(a, 99)  # NUEVO ARREGLO con el elemento agregado
print(b)  # [ 2  3  7  8  5 99]
print(a)  # [2 3 7 8 5]
# esto es posible: a = np.append(a, 99) Pero apunta a otro arreglo en memoria


[ 2  3  7  8  5 99]
[2 3 7 8 5]


In [11]:
# Pero, manipular un elemento es posible:
print("Modificar un elemento del arreglo original:")
print(a)  # [2 3 7 8 5]
a[2] = 99 # Modificar el tercer elemento del arreglo original
print(a)  # [ 2  3 99  8  5]
print("------------")
# Indexación Básica (Slicing)
# Como tambien acceder a elementos (## 🟦 Indexación y slicing)
print(a[0])    # primer elemento
print(a[-1])   # último elemento
print(a[1:4])  # elementos desde el índice 1 hasta el 3 (excluye el 4) 
print(a[:3])   # primeros 3 elementos (incluye 0, 1, 2)
print(a[2:])   # desde el índice 2 hasta el final
print(a[::-1])    # arreglo invertido


Modificar un elemento del arreglo original:
[2 3 7 8 5]
[ 2  3 99  8  5]
------------
2
5
[ 3 99  8]
[ 2  3 99]
[99  8  5]
[ 5  8 99  3  2]


In [12]:
###########CUIDADO CON LAS VISTAS (views) EN NUMPY ###########
# Referencias en el caso de slices (slicing) en NumPy
# Cuando haces un slice (selección de rango) en un array de NumPy, por defecto, también se devuelve una vista:
ar = np.array([7, 1, 9, 6, 3])
ars = ar[:3]
print("Original ar  :", ar)    # [7 1 9 6 3]
print("Slice ars  :", ars)   # [7 1 9]
print("Demostraion de que ars es una vista de ar (ars.base):", ars.base)
    # Demostraion de que ars es una vista de ar (ars.base): [7 1 9 6 3]
print("---")
print("El valor de id(ar) es igual al valor de id(ars.base):", id(ar) == id(ars.base)) # True  # Mismas direcciones de memoria
print("ar y ars.base apuntan al mismo objeto:", ar is ars.base) # True # is sirve para comparar si dos variables apuntan al mismo objeto en memoria
# NO HACER ESTO: # print(id(ar) is id(ars.base))  # Resultado: False ### RESULTADO NO ESPERADO
# RAZÓN:
# 1. 'id(objeto)' se llama dos veces, creando dos objetos de tipo 'int' (números).
# 2. El operador 'is' comprueba si son el MISMO objeto en memoria, no si tienen el mismo valor.
# 3. Aunque los VALORES de los ID son idénticos (porque ar y ars.base son el mismo array),
#    Python trata las dos llamadas a 'id()' como dos OBJETOS enteros DISTINTOS.

print("---")
# Pero ar y ars comparten la misma memoria para esos tres primeros elementos.
ars[1] = 22
print("Modified ar origin :", ar)
print("Modified ars[1]=22 :", ars)
print("---")
ar[0] = 11
print("Modified ar[0]=11 :", ar)
print("Modified ars view :", ars)
print("---")

### NOTA: En las listas normales de Python no ocurre lo mismo: el slice de una lista es una copia superficial, no una vista.
print("IMPORTANTE: lista normal en Python no comparte memoria en slices:")
l = [7, 1, 9, 6, 3]
ls = l[:3]      # slice de lista
ls[1] = 22
print(l)   # [7, 1, 9, 6, 3]  ← no cambia
print(ls)  # [7, 22, 9]

Original ar  : [7 1 9 6 3]
Slice ars  : [7 1 9]
Demostraion de que ars es una vista de ar (ars.base): [7 1 9 6 3]
---
El valor de id(ar) es igual al valor de id(ars.base): True
ar y ars.base apuntan al mismo objeto: True
---
Modified ar origin : [ 7 22  9  6  3]
Modified ars[1]=22 : [ 7 22  9]
---
Modified ar[0]=11 : [11 22  9  6  3]
Modified ars view : [11 22  9]
---
IMPORTANTE: lista normal en Python no comparte memoria en slices:
[7, 1, 9, 6, 3]
[7, 22, 9]


In [13]:
# Subarreglos mediante Fancy Indexing (Selección no Contigua) #  [[]]
# Acceso a elementos (indexing) 
z = np.array([2, 3, 77, 8, 55, 10, 6, 1, 44, 9])
sub_z = z[[2, 4, 5, 8]] # Acceder a elementos en las posiciones 2 y 4
print(sub_z)  # [77 55 10 44]   # Subarreglo con los elementos en las posiciones 2 y 4
sub2_z = z[[True, True, False, True, False, False, True, True, False, True]]
print(sub2_z)  # [ 2  3  8  6  1  9]   # Subarreglo con los elementos donde el índice booleano es True
print("---- Máscara booleana ----")
# sub3_z = z[[True, False*8, True]] # ERROR
# Crea la lista (como mascara): [True] + [False, False, ..., False] (8 veces) + [True]
mascara_correcta = [True] + [False] * 8 + [True]
sub3_z = z[mascara_correcta]
print(sub3_z)  # [2 9]   # Subarreglo con los elementos donde el índice booleano es True
# fancy indexing es una técnica para acceder a múltiples elementos de un arreglo utilizando listas o arreglos de índices.
# El Fancy Indexing permite seleccionar un subconjunto de datos eligiendo elementos no contiguos (saltados o desordenados), a diferencia de la indexación básica que solo selecciona rangos continuos.

[77 55 10 44]
[2 3 8 6 1 9]
---- Máscara booleana ----
[2 9]


In [18]:
# OPERACIONES ESTADÍSTICAS

datos = np.array([10, 20, 30, 40, 50])

print("\nPromedio:", np.mean(datos))
print("Máximo:", np.max(datos))
print("Mínimo:", np.min(datos))
print("Suma:", np.sum(datos))
print("Desviación estándar:", round(np.std(datos), 4))
print("Mediana:", np.median(datos))
print("Varianza:", np.var(datos))
print("Percentil 25:", np.percentile(datos, 25))
print("Percentil 75:", np.percentile(datos, 75))
print("Rango intercuartílico (IQR):", np.percentile(datos, 75) - np.percentile(datos, 25))




Promedio: 30.0
Máximo: 50
Mínimo: 10
Suma: 150
Desviación estándar: 14.1421
Mediana: 30.0
Varianza: 200.0
Percentil 25: 20.0
Percentil 75: 40.0
Rango intercuartílico (IQR): 20.0


In [6]:
### Operaciones vectorizadas
## Suma y resta de vectores
# Operaciones aritméticas entre arreglos del mismo tamaño:
u = np.array([0, 1])
v = np.array([1, 0])
z = u + v     # array([1, 1])
# z = np.add(u, v)
print(z)

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print("\nSuma de vectores:")
print(A + B) # [5 7 9]

total = A.sum()
print("\nSuma de los elementos de A (fila):")
print(total)  # Resultado: 6


[1 1]

Suma de vectores:
[5 7 9]

Suma de los elementos de A (fila):
6


In [15]:
### Suma con escalar

u = np.array([1, 3, -1, 2])
z = u + 10     # array([11, 13,  9, 12])
print(z)

[11 13  9 12]


In [16]:
### Multiplicación por escalar

y = np.array([1, 3])
z = 2 * y     # array([2, 6])
print(z)

[2 6]


In [ ]:
## 🟧 5. ### Producto Hadamard (multiplicación elemento a elemento)

u = np.array([1, 2])
v = np.array([3, 2])
z = u * v     # array([3, 4])
print(z)
'''
Nota:  los vectores deben ser del mismo tamaño para realizar operaciones aritméticas entre ellos
(suma, resta, multiplicación elemento a elemento, etc.).
Si los tamaños no coinciden, NumPy intentará aplicar reglas de broadcasting,
pero si no es posible, se generará un error.
Ej: # ValueError: operands could not be broadcast together with shapes (2,) (5,) 
'''

[3 4]


In [ ]:
## 🟨 6. ### Producto punto (dot product) (resultado = escalar)
# Es equivalente a la suma de los productos elemento a elemento.
# En álgebra lineal se denota como u·v o ⟨u, v⟩
# en álgebra lineal, el producto punto es simplemente un caso especial del producto matricial.
# se diferencia del producto Hadamard en que el resultado en el producto punto es un escalar.
u = np.array([1, 2])
v = np.array([3, 2])
# Internamente NumPy interpreta cada vector como una matriz 1×n y n×1.
z = u @ v   
# (1*3 + 2*2) = 7
print(z) # 7
# z = np.dot(u, v) 

'''
Nota: los vectores deben ser del mismo tamaño para realizar operaciones aritméticas entre ellos
Ej de erro:
# ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 5)

''' 


7


In [13]:
fnc_vector = np.vectorize(lambda x: x**2)
arr = np.array([1, 2, 3, 4, 5])
squared_arr = fnc_vector(arr)
print("Arreglo original:", arr)
print("Arreglo al cuadrado:", squared_arr) # Arreglo al cuadrado: [ 1  4  9 16 25]

print("\n---- Otro ejemplo de función vectorizada ----")
#otro ejemplo de función vectorizada: # En dos partes
def add_five(x):
    return x + 5
arr2 = np.array([10, 20, 30, 40])
fnc_vect_add_five = np.vectorize(add_five)
result_add_five = fnc_vect_add_five(arr2)
print("Arreglo original:", arr2)
print("Arreglo con 5 agregado a cada elemento:", result_add_five)


Arreglo original: [1 2 3 4 5]
Arreglo al cuadrado: [ 1  4  9 16 25]

---- Otro ejemplo de función vectorizada ----
Arreglo original: [10 20 30 40]
Arreglo con 5 agregado a cada elemento: [15 25 35 45]


In [ ]:
# Ejemplo de uso de np.linalg.solve() para resolver un sistema de ecuaciones lineales
A = np.array([[2, 1],
              [1, 3]])
# La matriz A debe ser: ✔ cuadrada ✔ tener solución única ✔ no ser singular (determinante ≠ 0)
R = np.array([5, 7])
X = np.linalg.solve(A, R)
print(X) # [1.6 1.8]
# Esto significa:
# x = 1.6
# y = 1.8

'''
Ejemplo práctico: resolver un sistema de ecuaciones lineales con np.linalg.solve()
Dia1) Se compra 2 manzanas + 1 naranja = $5
Dia2) Se compra 1 manzana + 3 naranjas = $7
Calcular el el precio individual.
De la FORMA:
2x + y = 5
x + 3y = 7
'''
Matriz_A = np.array([[2, 1], [1, 3]])
Matriz_R = np.array([5, 7])
solucion = np.linalg.solve(Matriz_A, Matriz_R)
print("Precio de la manzana (x):", solucion[0])  # Precio de la manzana
print("Precio de la naranja (y):", solucion[1])   # Precio de la naranja



[1.6 1.8]
Precio de la manzana (x): 1.6
Precio de la naranja (y): 1.8


In [ ]:
# 
'''
Regresión lineal (modelo predictivo)

REGRESIÓN LINEAL — MODELO PREDICTIVO
La regresión lineal permite estimar el valor de una variable
(en este caso el precio) a partir de otras variables.

Entre más variables, se necesitas más observaciones para poder estimarlas correctamente.
Aunque normalmente no se busca una solución exacta, sino un modelo que estime los precios.
Más variables → necesitas más datos
Datos reales → modelo estadístico
Ej:
variables independientes#
estrato (2, 3, 4) # Estrato socioeconómico 4 tiene mas Valor
conectividad (1, 2, 3) # Clasificacion 3 tiene mas valor
número de cuartos # En general, más cuartos → más valor
número de baños # En general, más baños → más valor
área (m²) # En general, más área → más valor

variables independientes:
Precio
'''
# LOGICA:
'''
Variables numéricas (se usan directamente)
✔ estrato → 2, 3, 4
✔ cuartos → 1, 2
✔ baños → 1, 2
✔ área → 45, 60, 80…

Cuándo normalizar, se recomendable si:
hay rangos muy diferentes
usarás machine learning
usarás gradiente descendente

El modelo usará:
Precio = b0 + b1(estrato) + b2(conectividad) + b3(cuartos) + b4(baños) + b5(area) 
En forma matricial:
AX = B
donde:
A = variables
X = coeficientes que queremos encontrar
B = precios reales

## Ejemplo con 10 observaciones (Bogotá) (Se recomienda +50)
### 📊 Datos de ejemplo
| Estrato | Conectividad | Cuartos | Baños | Área | Precio (millones COP) |
| ------- | ------------ | ------- | ----- | ---- | --------------------- |
| 2       | 1            | 1       | 1     | 45   | 120                   |
| 2       | 2            | 2       | 1     | 55   | 150                   |
| 3       | 2            | 2       | 2     | 65   | 210                   |
| 3       | 3            | 2       | 2     | 70   | 240                   |
| 4       | 3            | 3       | 2     | 90   | 360                   |
| 4       | 2            | 3       | 2     | 85   | 330                   |
| 3       | 1            | 1       | 1     | 50   | 140                   |
| 2       | 1            | 2       | 1     | 60   | 160                   |
| 4       | 3            | 3       | 3     | 110  | 480                   |
| 3       | 2            | 2       | 1     | 75   | 220                   |
'''

# Variables independientes
A = np.array([
    [2,1,1,1,45],
    [2,2,2,1,55],
    [3,2,2,2,65],
    [3,3,2,2,70],
    [4,3,3,2,90],
    [4,2,3,2,85],
    [3,1,1,1,50],
    [2,1,2,1,60],
    [4,3,3,3,110],
    [3,2,2,1,75]
])

# Precios reales
B = np.array([120,150,210,240,360,330,140,160,480,220])

# Añadimos columna de 1s para el intercepto (b0)
unos = np.ones((A.shape[0], 1))
A = np.hstack((unos, A))

# Resolver usando mínimos cuadrados
coeficientes, _, _, _ = np.linalg.lstsq(A, B, rcond=None)





print("Coeficientes del modelo:")
print(coeficientes)

# 
'''
Regresión lineal (modelo predictivo)
Entre más variables, se necesitas más observaciones para poder estimarlas correctamente.
Aunque normalmente no se busca una solución exacta, sino un modelo que estime los precios.
Más variables → necesitas más datos
Datos reales → modelo estadístico
Ej:
variables independientes#
estrato (2, 3, 4) # Estrato socioeconómico 4 tiene mas Valor
conectividad (1, 2, 3) # Clasificacion 3 tiene mas valor
número de cuartos # En general, más cuartos → más valor
número de baños # En general, más baños → más valor
área (m²) # En general, más área → más valor

variables independientes:
Precio
'''
# LOGICA:
'''
Variables numéricas (se usan directamente)
✔ estrato → 2, 3, 4
✔ cuartos → 1, 2
✔ baños → 1, 2
✔ área → 45, 60, 80…

Cuándo normalizar, se recomendable si:
hay rangos muy diferentes
usarás machine learning
usarás gradiente descendente

MODELO MATEMÁTICO:

Precio = b0 + b1(estrato) + b2(conectividad) + b3(cuartos) + b4(baños) + b5(area) 
En forma matricial:
AX = B
donde:
A = variables
X = coeficientes que queremos encontrar
B = precios reales

## Ejemplo con 10 observaciones (Bogotá) (Se recomienda +50)
### 📊 Datos de ejemplo
| Estrato | Conectividad | Cuartos | Baños | Área | Precio (millones COP) |
| ------- | ------------ | ------- | ----- | ---- | --------------------- |
| 2       | 1            | 1       | 1     | 45   | 120                   |
| 2       | 2            | 2       | 1     | 55   | 150                   |
| 3       | 2            | 2       | 2     | 65   | 210                   |
| 3       | 3            | 2       | 2     | 70   | 240                   |
| 4       | 3            | 3       | 2     | 90   | 360                   |
| 4       | 2            | 3       | 2     | 85   | 330                   |
| 3       | 1            | 1       | 1     | 50   | 140                   |
| 2       | 1            | 2       | 1     | 60   | 160                   |
| 4       | 3            | 3       | 3     | 110  | 480                   |
| 3       | 2            | 2       | 1     | 75   | 220                   |
'''

# -------------------------
# Variables independientes
# columnas:
# estrato, conectividad, cuartos, baños, área
# -------------------------

A = np.array([
    [2,1,1,1,45],
    [2,2,2,1,55],
    [3,2,2,2,65],
    [3,3,2,2,70],
    [4,3,3,2,90],
    [4,2,3,2,85],
    [3,1,1,1,50],
    [2,1,2,1,60],
    [4,3,3,3,110],
    [3,2,2,1,75]
])

# Precios reales (millones COP)
B = np.array([120,150,210,240,360,330,140,160,480,220])

# Añadimos columna de 1s para el intercepto (b0)
unos = np.ones((A.shape[0], 1))
# print("Columna de unos para el intercepto:")
print(unos)
A = np.hstack((unos, A))
# print("\nMatriz A después de agregar la columna de unos:")
# print(A)

# Resolver usando mínimos cuadrados
coeficientes, _, _, _ = np.linalg.lstsq(A, B, rcond=None)

print("Coeficientes del modelo:")
print(coeficientes)
# Coeficientes del modelo:
# [-148.687   11.478   -6.582   -1.045   38.284    4.388 ]
# [    b0  , estrato ,conectiv, cuartos , baños  ,   m^2 ]
'''
¿Qué obtienes con esto?

b0 = valor base del modelo
b1 = aumento por cada nivel de estrato
b2 = impacto de conectividad
b3 = impacto por cuartos
b4 = impacto por baños
b5 = aumento por cada m²

Interpretación:
• Cada baño adicional aumenta MUCHO el valor
• Estrato aumenta el valor
• Cada m² aumenta el precio
• Algunos coeficientes pueden ser negativos si
  los datos son pocos o inconsistentes
'''

# PREDICCIÓN DE UN NUEVO APARTAMENTO
'''
Ejemplo:
estrato=3
conectividad=2
cuartos=2
baños=1
área=80
'''

print("\nPredicción para un nuevo apartamento:")
print("Características: estrato=3, conectividad=2, cuartos=2, baños=1, área=80 m²")
nuevo = np.array([1, 3, 2, 2, 1, 80])  # incluye el 1 del intercepto
precio_estimado = nuevo @ coeficientes
print("\n---Precio estimado:---")
print(round(precio_estimado, 2), "millones COP")






Coeficientes del modelo:
[-148.687   11.478   -6.582   -1.045   38.284    4.388]
Matriz A antes de agregar la columna de unos:
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

Matriz A después de agregar la columna de unos:
[[  1.   2.   1.   1.   1.  45.]
 [  1.   2.   2.   2.   1.  55.]
 [  1.   3.   2.   2.   2.  65.]
 [  1.   3.   3.   2.   2.  70.]
 [  1.   4.   3.   3.   2.  90.]
 [  1.   4.   2.   3.   2.  85.]
 [  1.   3.   1.   1.   1.  50.]
 [  1.   2.   1.   2.   1.  60.]
 [  1.   4.   3.   3.   3. 110.]
 [  1.   3.   2.   2.   1.  75.]]
Coeficientes del modelo:
[-148.687   11.478   -6.582   -1.045   38.284    4.388]

Predicción para un nuevo apartamento:
Características: estrato=3, conectividad=2, cuartos=2, baños=1, área=80 m²

---Precio estimado:---
259.82 millones COP


In [ ]:
### `solve` 👉 resolver una ecuación matemática perfecta
### `lstsq` 👉 encontrar la **mejor línea que explica los datos reales**
### Ambas funciones resuelven sistemas lineales, pero **no se usan en las mismas situaciones**.

'''
## 🧠 1️ `np.linalg.solve(A, B)`
### ✔ Qué hace
Resuelve el sistema exacto:
AX = B
### ✔ Cuándo usarlo
✅ cuando el sistema tiene **una única solución exacta**
✅ cuando:
* número de ecuaciones = número de incógnitas
* matriz A es cuadrada (n×n)
* el sistema es consistente
''
import numpy as np
A = np.array([
    [2, 1],
    [1, 3]
])
B = np.array([8, 13])
# 2 ecuaciones // 2 incógnitas
X = np.linalg.solve(A, B) 
print(X)
#np.linalg.solve(A, B)
#con más filas que columnas ❌
#obtendrás error.
'''
##########
'''
---
## 🧠 2️ `np.linalg.lstsq(A, B, rcond=None)`
### ✔ Qué hace
Encuentra la **mejor solución aproximada** cuando:
* hay más ecuaciones que incógnitas
* los datos no permiten solución exacta
* hay ruido en los datos reales
Se llama:
✅ mínimos cuadrados
✅ best fit
✅ ajuste lineal
### ✔ Cuándo usarlo
✅ regresión lineal
✅ ciencia de datos
✅ datos reales con ruido
✅ sistemas sobredeterminados
### ✔ Ejemplo típico (como tu modelo)
Tienes:
✔ 10 apartamentos con sus caracteristicas y precios
✔ 5 variables a evaluar
➡️ no existe solución exacta
➡️ se busca la mejor aproximación
'''
# coeficientes, _, _, _ = np.linalg.lstsq(A, B, rcond=None)
'''
## 🎯 Diferencia CLAVE

| Función | Tipo de solución | Requisitos      | Uso típico                 |
| ------- | ---------------- | --------------- | -------------------------- |
| `solve` | exacta           | matriz cuadrada | física, ecuaciones exactas |
| `lstsq` | aproximada       | cualquier forma | datos reales, ML           |
'''

# **---Notas Teoricas---**

Los vectores y matrices son los bloques fundamentales del álgebra lineal.  
Permiten representar y manipular datos de forma eficiente.  

✔ Un VECTOR puede representar:   
    - coordenadas espaciales (x, y, z)  
    - lista de valores  
    - características de un usuario  
    - pixeles de una imagen  

✔ Una MATRIZ puede representar:  
    - transformaciones geométricas  
    - datos tabulares  
    - redes neuronales  
    - sistemas de ecuaciones  

El álgebra lineal es base de:  
    física, ingeniería, economía,  
    gráficos 3D, inteligencia artificial,  
    ciencia de datos y machine learning.  